In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data=pd.read_table("fruit_data_with_colors.txt")
print(data.isna().sum())

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             0
width            0
height           0
color_score      0
dtype: int64


In [5]:
print(data.head())

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79


In [6]:
x=data[['mass', 'width', 'height', 'color_score']]
y=data['fruit_label']

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [8]:
from sklearn.preprocessing import MinMaxScaler
minax=MinMaxScaler(feature_range=(0,1))
x_train=minax.fit_transform(x_train)
x_test=minax.transform(x_test)

In [9]:
print(x_test)

[[0.1958042  0.         0.74603175 0.47368421]
 [0.34965035 0.42105263 0.50793651 0.13157895]
 [0.25874126 0.34210526 0.61904762 0.52631579]
 [0.41958042 0.39473684 0.9047619  0.44736842]
 [0.23776224 0.26315789 0.53968254 0.52631579]
 [0.23076923 0.47368421 0.6031746  0.52631579]
 [0.28671329 0.36842105 0.6031746  0.57894737]
 [0.3006993  0.42105263 0.50793651 0.78947368]
 [0.27972028 0.42105263 0.53968254 0.76315789]
 [0.14685315 0.02631579 0.63492063 0.44736842]
 [0.43356643 0.39473684 1.03174603 0.44736842]
 [0.03496503 0.10526316 0.11111111 0.65789474]]


In [10]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [11]:
y_pred=model.predict(x_test)
print(y_pred)

[4 1 1 4 1 1 1 1 1 4 4 1]


In [12]:
print("{:.2f}".format(model.score(x_train,y_train)))

0.70


In [13]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'.format(model.score(x_test,y_test)))

Accuracy of Logistic Regression classifier on training set: 0.58


In [14]:
print('Accuracy of Logistic Regression classifier on test set: {:.2f}'.format(model.score(x_test,y_test)))

Accuracy of Logistic Regression classifier on test set: 0.58


In [15]:
modl_dat=pd.concat([pd.DataFrame(y_test).reset_index().drop(columns=["index"]),pd.DataFrame(y_pred).reset_index().drop(columns=["index"])],axis=1)
modl_dat.rename(columns={0:"Predicted"},inplace=True)
print(modl_dat.head())

   fruit_label  Predicted
0            4          4
1            1          1
2            3          1
3            4          4
4            3          1


In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy score : {:.2f}".format(accuracy_score(modl_dat["fruit_label"],modl_dat["Predicted"])))
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred))

Accuracy score : 0.58
Confusion matrix : 
 [[3 0 0 0]
 [1 0 0 0]
 [4 0 0 0]
 [0 0 0 4]]


In [17]:
print(classification_report(modl_dat["fruit_label"],modl_dat["Predicted"]))

              precision    recall  f1-score   support

           1       0.38      1.00      0.55         3
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         4
           4       1.00      1.00      1.00         4

    accuracy                           0.58        12
   macro avg       0.34      0.50      0.39        12
weighted avg       0.43      0.58      0.47        12



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
