In [141]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [142]:
data=pd.read_table("fruit_data_with_colors.txt")
print(data.isna().sum())

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             0
width            0
height           0
color_score      0
dtype: int64


In [143]:
print(data.head())

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79


In [144]:
x=data[['mass', 'width', 'height', 'color_score']]
y=data["fruit_label"]

In [145]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [146]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [147]:
from sklearn.svm import SVC
model=SVC(kernel="rbf")
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)

[3 3 4 3 1 1 3 4 3 1 2 1]


In [148]:
mdl_data=pd.concat([pd.DataFrame(y_test).reset_index(drop=True),pd.DataFrame(y_pred).reset_index(drop=True)],axis=1)
mdl_data.rename(columns={0:"Predicted_data"},inplace=True)
print(mdl_data.head())

   fruit_label  Predicted_data
0            3               3
1            3               3
2            4               4
3            3               3
4            1               1


In [149]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("Confussion matrix : \n",confusion_matrix(mdl_data["fruit_label"],mdl_data["Predicted_data"]))
print("Accuracy score : {:.2f}".format(accuracy_score(mdl_data["fruit_label"],mdl_data["Predicted_data"])))

Confussion matrix : 
 [[4 0 0 0]
 [0 1 0 0]
 [0 0 5 0]
 [0 0 0 2]]
Accuracy score : 1.00


In [150]:
print("Classification report : ")
print(classification_report(mdl_data["fruit_label"],mdl_data["Predicted_data"]))

Classification report : 
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         2

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12

